### ISSUE TITLE
Implementation choice of scatter_dataset function

### ISSUE THREAD

**Issue by Guriido** [chainer/chainermn#208]
I have a question regarding the implementation of  [scatter_dataset](https://github.com/chainer/chainermn/blob/master/chainermn/datasets/scatter_dataset.py) function.

The dataset of root worker is effectively broadcasted to every worker instead of being scattered.
Most of the data get by each of the workers is actually unused, as they create a `SubDataset` object from it.

I understand that scattering the whole dataset to the workers would require to handle shuffling before scatter (and eventually unsure the data contingency of sent buffers), and deal with another implementation of `Dataset` , as the current `SubDataset` operates as if the process disposed of the whole dataset; but it would avoid a lot of communication (theoretically it would divide the communication cost by `comm.size` ).

For relatively tiny datasets such as mnist, I guess it would not make much difference, but maybe for huge datasets like ImageNet, the dataset could be scattered within a few hours ? (which could be affordable considering the necessary training time of big models on this dataset)
What do you think about it ?

**Comment by kuenishi** [comment]
It assumes references to actual images, movies or any others, but not actual data itself. For example, you can see our [ImageNet example](https://github.com/chainer/chainermn/tree/v1.2.0/examples/imagenet) that is actually using [pairs of file path and corresponding label](https://github.com/chainer/chainer/blob/v3.4.0/chainer/datasets/image_dataset.py#L112-L118), thought it is not obvious from code. For example, if there are million file paths with 128B length each, the size of Dataset object to be scattered would be around 128MB with some overhead of Python string and list entries per file path. I'd recommend scattering dataset by references like our examples and loading actual data at each process from some shared file systems like NFS or S3 in a distributed manner, because otherwise I/O bandwidth of root node could be bottleneck before starting training.

**Comment by Guriido** [comment]
Thank you very much for your answer, it makes things clear for me. 
This detail was also explained in **Copying datasets** section of [documentation](http://chainermn.readthedocs.io/en/latest/tutorial/step1_communicators_optimizers.html), I may have overlooked this passage..

In this case, I guess broadcasting labels instead of scattering them does not make much difference.
