### ISSUE TITLE
Running chainermn scripts without mpirun / mpiexec

### ISSUE THREAD

**Issue by andremoeller** [chainer/chainermn#209]
Hi,

Suppose I want to run a distributed training script on two hosts (host0 and host1) using chainermn.

Is there a way I could run

`python my_chainermn_script.py`

on both host0 and host1 instead of doing 

`mpiexec --host host0,host1 my_chainermn_script.py`

or

`mpirun --host host0,host1 my_chainermn_script.py`

from either host0 or host1?

Thanks.

**Comment by keisukefukuda** [comment]
Currently, ChainerMN depends on MPI and I'm afraid there's not (simple way) to do that.
You can execute `mpiexec` command from another python script or a shell script, but not from the chainermn_script.py itself.

I'm curious about your motivation to avoid `mpiexec`. Do you want to remove MPI dependency of ChainerMN, or just want to kick the script from a single script file?
Or do you want to do pre-processing with a single process before starting ChainerMN ?

**Comment by keisukefukuda** [comment]
Andre,

Thanks for the additional info.
🤔 

Unfortunately, I'm afraid there's no simple way to do that, AFAIK.
The simplest way that I think of is to collect the hostnames and kick `mpiexec` from one node.

Actually, there would be 2 *complicated* ways to do that. First, if you know what `mpiexec` actually does, just mimic what it. Second, you can write your own MPI code to create a new communicator dynamically. See "James T. (Intel)  Tue, 02/21/2012 - 14:42" in [1].
Anyways, both methods are *far* from simple. 

[1] https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/279685

**Comment by andremoeller** [comment]
Thanks!
>  you know what mpiexec actually does, just mimic what it. It's far from simple.

Is the source code for `mpiexec` open? I haven't been able to find it. Otherwise, I suppose the OpenMPI documentation has good information on what `mpiexec` actually does. Are there any other good sources of information on the details of `mpiexec`, detailed to the point that we can mimic some subset of the functionality?

Thank you.

**Comment by keisukefukuda** [comment]
> Is the source code for mpiexec open?
It depends on your environment. There are two major open source implementations of MPI: Open MPI and MVAPICH (and Mvapich). Actually, most vendor implementations are based on one of them.
I don't recommend to do that. MPI codebase is huge and `mpiexec` does a lot of things. The MPI specification requires that MPI processes are run by `mpiexec`. 

Another possible option is to start your processes via `mpiexec` from the starting. `mpiexec` does not affect non-MPI programs. They just run in parallel independently. Only MPI programs read the appropriate environment variables and communicate each other.

**Comment by andremoeller** [comment]
Thanks for your replies, Keisuke.

`The simplest way that I think of is to collect the hostnames and kick mpiexec from one node.`

This is what I'm currently doing, but the goal is to get rid of mpiexec altogether, since in this case, I'd still have nodes sshing to each other just to start processes that they could (possibly) just start themselves.

**Comment by keisukefukuda** [comment]
I guess what you are doing now is the best way for two reasons.

(1)
First, MPI assumes that programs are started from `mpiexec`. It's the specification.

(2)
Even if there's a way to launch MPI processes in another method, you need to collect a list of nodes, decide how to assign processes/ranks to the nodes anyways, and all processes/ranks must agree to this decision *1. This is because the launched processes need to communicate each other and work together. This is an essential step, no matter what method you use (no matter MPI or non-MPI-something, mpiexec or non-mpiexec-something). There's not a big difference from what you are doing and things wouldn't be simpler *2.

[*1] This step is called "rendezvous" in general. You need to aggregate information to one place anyways.

[*2] Facebook has an MPI-alternative called Gloo. It uses Redis database for rendezvous coordination. I don't think it's any simpler.

I think it's the final answer from me, and actually, it's not about ChainerMN but about MPI in general, so I'm closing the issue. 

Thanks!
Keisuke

**Comment by andremoeller** [comment]
Now that you put it that way, you're right that I'd have to do rendezvous no matter what, and mpiexec makes this simpler. I'm pretty convinced that this is the best way to do things even if it's not the ideal in my particular case.

`it's not about ChainerMN but about MPI in general, so I'm closing the issue.`

Yes, I think you are right about this. At any rate, thank you for your help!
