### ISSUE TITLE
Guidance on MVAPICH vs OpenMPI

### ISSUE THREAD

**Issue by andremoeller** [chainer/chainermn#210]
Hi,

Both MVAPICH and OpenMPI are cuda-aware, but which one does Chainer recommend / for which circumstances? Which MPI implementation was used in the results here? https://chainer.org/general/2017/02/08/Performance-of-Distributed-Deep-Learning-Using-ChainerMN.html

Thank you.

**Comment by keisukefukuda** [comment]
Hi,

In the blog post article, we used Mvapich2. However, we are moving to OpenMPI 2.1 series due to Mvapich's several crashing bugs.

Unfortunately, Open MPI 3.0.0 has another issue that large size of GPU-Direct RDMA data transfer does not work properly. We recommend Open MPI 2.1.x.

I hope I'm answering your question. I'm closing this issue, but please feel free to reopen it if you have further quesions.

Thanks!
Keisuke
