### ISSUE TITLE
Don't inicialize global NCCL comm when 

### ISSUE THREAD

**Issue by undertherain** [chainer/chainermn#224]
init_comms function in communicators/_communication_utility.py seems to be oblivious about which  communicator in chainermn terms will be used. 

As a result global nccl_comm is being initialized along with intra_nccl_comm even if hierarchical_comm (i.e. not using NCCL globally) is requested from chainermn.

This causes a problem as on some systems NCCL fails when initializing on too many (around 512 in our case) GPUs. This would have been avoided if chainermn  did not initialize nccl_comm when it is not needed.

**Comment by kuenishi** [comment]
Thank  you for pointing it out. We didn't assume that use case where hierarchical communicator was used along with NCCL 2, because it was for non-RDMA (e.g. TCP/IP) inter-node communication along with *NCCL1*. With NCCL2 pure NCCL communicator seemed to be the best choice for that inter-node communication pattern. We'll consider adding that choice in the next release.

**Comment by kuenishi** [comment]
This issue will be addressed by #257 and will be shipped as 1.3.0.
